Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Caliburn.Controllers
{
    public class RentalsController : Controller
    {
        // GET: Rentals
        public ActionResult New()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Caliburn Cinema Rentals</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Caliburn Cinema Rentals</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
	<div class="container">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		</button>
		<a class="navbar-brand" href="/">Caliburn Cinema Rentals</a>
		<div class="navbar-collapse collapse" id="navbarSupportedContent">
			<ul class="nav navbar-nav mr-auto">
				<li>@Html.ActionLink("New Rental", "New", "Rentals")</li>
				<li>@Html.ActionLink("Customers", "Index", "Customers")</li>
				<li>@Html.ActionLink("Movies", "Index", "Movies")</li>
			</ul>

			<ul class="nav navbar-nav navbar-right mr-auto">
				<li class="nav-item"><a href="/Account/Register" id="registerLink" class="nav-link">Register</a></li>
				<li class="nav-item"><a href="/Account/Login" id="loginLink" class="nav-link">Log in</a></li>
			</ul>

		</div>
	</div>
</nav>